# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Subject_Tester.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1025, 260)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(50, 10, 911, 181))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.verticalLayout.setContentsMargins(0, -1, 0, -1)
        self.verticalLayout.setObjectName("verticalLayout")
        self.btnStartSession = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnStartSession.sizePolicy().hasHeightForWidth())
        self.btnStartSession.setSizePolicy(sizePolicy)
        self.btnStartSession.setObjectName("btnStartSession")
        self.verticalLayout.addWidget(self.btnStartSession)
        self.OpenMonitor = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.OpenMonitor.sizePolicy().hasHeightForWidth())
        self.OpenMonitor.setSizePolicy(sizePolicy)
        self.OpenMonitor.setObjectName("OpenMonitor")
        self.verticalLayout.addWidget(self.OpenMonitor)
        self.lblTrialNumber = QtWidgets.QLabel(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblTrialNumber.sizePolicy().hasHeightForWidth())
        self.lblTrialNumber.setSizePolicy(sizePolicy)
        self.lblTrialNumber.setObjectName("lblTrialNumber")
        self.verticalLayout.addWidget(self.lblTrialNumber)
        self.gridLayout.addLayout(self.verticalLayout, 0, 1, 1, 1)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.btnStartTrial = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnStartTrial.sizePolicy().hasHeightForWidth())
        self.btnStartTrial.setSizePolicy(sizePolicy)
        self.btnStartTrial.setMaximumSize(QtCore.QSize(200, 16777215))
        self.btnStartTrial.setObjectName("btnStartTrial")
        self.verticalLayout_2.addWidget(self.btnStartTrial)
        self.btnStop = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnStop.sizePolicy().hasHeightForWidth())
        self.btnStop.setSizePolicy(sizePolicy)
        self.btnStop.setMaximumSize(QtCore.QSize(600, 16777215))
        self.btnStop.setObjectName("btnStop")
        self.verticalLayout_2.addWidget(self.btnStop)
        self.gridLayout.addLayout(self.verticalLayout_2, 0, 2, 1, 1)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.formLayout.setFieldGrowthPolicy(QtWidgets.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setObjectName("formLayout")
        self.lblSubject = QtWidgets.QLabel(self.gridLayoutWidget)
        self.lblSubject.setObjectName("lblSubject")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.lblSubject)
        self.txtSubject = QtWidgets.QPlainTextEdit(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txtSubject.sizePolicy().hasHeightForWidth())
        self.txtSubject.setSizePolicy(sizePolicy)
        self.txtSubject.setMaximumSize(QtCore.QSize(500, 16777215))
        self.txtSubject.setObjectName("txtSubject")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.txtSubject)
        self.lblAge = QtWidgets.QLabel(self.gridLayoutWidget)
        self.lblAge.setObjectName("lblAge")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.lblAge)
        self.txtAge = QtWidgets.QPlainTextEdit(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txtAge.sizePolicy().hasHeightForWidth())
        self.txtAge.setSizePolicy(sizePolicy)
        self.txtAge.setMaximumSize(QtCore.QSize(500, 16777215))
        self.txtAge.setObjectName("txtAge")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.txtAge)
        self.lblGender = QtWidgets.QLabel(self.gridLayoutWidget)
        self.lblGender.setObjectName("lblGender")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.lblGender)
        self.txtGender = QtWidgets.QPlainTextEdit(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txtGender.sizePolicy().hasHeightForWidth())
        self.txtGender.setSizePolicy(sizePolicy)
        self.txtGender.setMaximumSize(QtCore.QSize(500, 16777215))
        self.txtGender.setObjectName("txtGender")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.txtGender)
        self.lblMass = QtWidgets.QLabel(self.gridLayoutWidget)
        self.lblMass.setObjectName("lblMass")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.lblMass)
        self.txtMass = QtWidgets.QPlainTextEdit(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txtMass.sizePolicy().hasHeightForWidth())
        self.txtMass.setSizePolicy(sizePolicy)
        self.txtMass.setMaximumSize(QtCore.QSize(500, 16777215))
        self.txtMass.setObjectName("txtMass")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.txtMass)
        self.xtxHeight = QtWidgets.QPlainTextEdit(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.xtxHeight.sizePolicy().hasHeightForWidth())
        self.xtxHeight.setSizePolicy(sizePolicy)
        self.xtxHeight.setMaximumSize(QtCore.QSize(500, 16777215))
        self.xtxHeight.setObjectName("xtxHeight")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.xtxHeight)
        self.lblLegLength = QtWidgets.QLabel(self.gridLayoutWidget)
        self.lblLegLength.setObjectName("lblLegLength")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.lblLegLength)
        self.txtLegLength = QtWidgets.QPlainTextEdit(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txtLegLength.sizePolicy().hasHeightForWidth())
        self.txtLegLength.setSizePolicy(sizePolicy)
        self.txtLegLength.setMaximumSize(QtCore.QSize(500, 16777215))
        self.txtLegLength.setObjectName("txtLegLength")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.txtLegLength)
        self.lblheight = QtWidgets.QLabel(self.gridLayoutWidget)
        self.lblheight.setObjectName("lblheight")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.lblheight)
        self.gridLayout.addLayout(self.formLayout, 0, 0, 1, 1)
        self.gridLayoutWidget.raise_()
        self.lblSubject.raise_()
        self.txtSubject.raise_()
        self.txtAge.raise_()
        self.lblAge.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1025, 27))
        self.menubar.setObjectName("menubar")
        self.menuSubject = QtWidgets.QMenu(self.menubar)
        self.menuSubject.setObjectName("menuSubject")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menuSubject.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btnStartSession.setText(_translate("MainWindow", "Start Session"))
        self.OpenMonitor.setText(_translate("MainWindow", "open monitor"))
        self.lblTrialNumber.setText(_translate("MainWindow", "Trial 00"))
        self.btnStartTrial.setText(_translate("MainWindow", "Record"))
        self.btnStop.setText(_translate("MainWindow", "Stop"))
        self.lblSubject.setText(_translate("MainWindow", "Subject number"))
        self.lblAge.setText(_translate("MainWindow", "Age"))
        self.lblGender.setText(_translate("MainWindow", "Gender"))
        self.lblMass.setText(_translate("MainWindow", "Mass"))
        self.lblLegLength.setText(_translate("MainWindow", "Leg Length"))
        self.lblheight.setText(_translate("MainWindow", "Height"))
        self.menuSubject.setTitle(_translate("MainWindow", "Subject "))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

