# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Subject_Tester.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtWidgets

from Managers import SessionManger


class Ui_MainWindow(SessionManger.SessionManager):

    def __init__(self):
        self.MainWindow = QtWidgets.QMainWindow()
        self.setupUi(self.MainWindow)

        lbl_ = [self.lblAge, self.lblGender, self.lblheight, self.lblLegLength, self.lblheight, self.lblMass,
                self.lblTrialNumber, self.lblPort]
        btn_ = [self.btnConnect, self.btnOpenMonitor, self.btnRecord, self.btnStartSession, self.btnStop]
        txt_ = [self.txtAge, self.txtGender, self.txtHost, self.txtLegLength, self.txtMass, self.txtPort,
                self.txtSubject]

        super(Ui_MainWindow, self).__init__(btn_, txt_, lbl_)

        self.MainWindow.show()


    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1025, 254)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(50, 10, 911, 187))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.gridLayout.setObjectName("gridLayout")
        self.boxSession = QtWidgets.QVBoxLayout()
        self.boxSession.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.boxSession.setContentsMargins(0, -1, 0, -1)
        self.boxSession.setObjectName("boxSession")
        self.btnStartSession = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.btnStartSession.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnStartSession.sizePolicy().hasHeightForWidth())
        self.btnStartSession.setSizePolicy(sizePolicy)
        self.btnStartSession.setObjectName("btnStartSession")
        self.boxSession.addWidget(self.btnStartSession)
        self.btnOpenMonitor = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.btnOpenMonitor.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnOpenMonitor.sizePolicy().hasHeightForWidth())
        self.btnOpenMonitor.setSizePolicy(sizePolicy)
        self.btnOpenMonitor.setObjectName("btnOpenMonitor")
        self.boxSession.addWidget(self.btnOpenMonitor)
        self.lblTrialNumber = QtWidgets.QLabel(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblTrialNumber.sizePolicy().hasHeightForWidth())
        self.lblTrialNumber.setSizePolicy(sizePolicy)
        self.lblTrialNumber.setObjectName("lblTrialNumber")
        self.boxSession.addWidget(self.lblTrialNumber)
        self.gridLayout.addLayout(self.boxSession, 0, 2, 1, 1)
        self.boxTrial = QtWidgets.QVBoxLayout()
        self.boxTrial.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.boxTrial.setObjectName("boxTrial")
        self.btnRecord = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.btnRecord.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnRecord.sizePolicy().hasHeightForWidth())
        self.btnRecord.setSizePolicy(sizePolicy)
        self.btnRecord.setMaximumSize(QtCore.QSize(200, 16777215))
        self.btnRecord.setObjectName("btnRecord")
        self.boxTrial.addWidget(self.btnRecord)
        self.btnStop = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.btnStop.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnStop.sizePolicy().hasHeightForWidth())
        self.btnStop.setSizePolicy(sizePolicy)
        self.btnStop.setMaximumSize(QtCore.QSize(600, 16777215))
        self.btnStop.setObjectName("btnStop")
        self.boxTrial.addWidget(self.btnStop)
        self.gridLayout.addLayout(self.boxTrial, 0, 3, 1, 1)
        self.boxInfo = QtWidgets.QFormLayout()
        self.boxInfo.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.boxInfo.setFieldGrowthPolicy(QtWidgets.QFormLayout.AllNonFixedFieldsGrow)
        self.boxInfo.setObjectName("boxInfo")
        self.lblSubject = QtWidgets.QLabel(self.gridLayoutWidget)
        self.lblSubject.setObjectName("lblSubject")
        self.boxInfo.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.lblSubject)
        self.txtSubject = QtWidgets.QPlainTextEdit(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txtSubject.sizePolicy().hasHeightForWidth())
        self.txtSubject.setSizePolicy(sizePolicy)
        self.txtSubject.setMaximumSize(QtCore.QSize(500, 16777215))
        self.txtSubject.setObjectName("txtSubject")
        self.boxInfo.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.txtSubject)
        self.lblAge = QtWidgets.QLabel(self.gridLayoutWidget)
        self.lblAge.setObjectName("lblAge")
        self.boxInfo.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.lblAge)
        self.txtAge = QtWidgets.QPlainTextEdit(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txtAge.sizePolicy().hasHeightForWidth())
        self.txtAge.setSizePolicy(sizePolicy)
        self.txtAge.setMaximumSize(QtCore.QSize(500, 16777215))
        self.txtAge.setObjectName("txtAge")
        self.boxInfo.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.txtAge)
        self.lblGender = QtWidgets.QLabel(self.gridLayoutWidget)
        self.lblGender.setObjectName("lblGender")
        self.boxInfo.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.lblGender)
        self.txtGender = QtWidgets.QPlainTextEdit(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txtGender.sizePolicy().hasHeightForWidth())
        self.txtGender.setSizePolicy(sizePolicy)
        self.txtGender.setMaximumSize(QtCore.QSize(500, 16777215))
        self.txtGender.setObjectName("txtGender")
        self.boxInfo.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.txtGender)
        self.lblMass = QtWidgets.QLabel(self.gridLayoutWidget)
        self.lblMass.setObjectName("lblMass")
        self.boxInfo.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.lblMass)
        self.txtMass = QtWidgets.QPlainTextEdit(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txtMass.sizePolicy().hasHeightForWidth())
        self.txtMass.setSizePolicy(sizePolicy)
        self.txtMass.setMaximumSize(QtCore.QSize(500, 16777215))
        self.txtMass.setObjectName("txtMass")
        self.boxInfo.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.txtMass)
        self.lblheight = QtWidgets.QLabel(self.gridLayoutWidget)
        self.lblheight.setObjectName("lblheight")
        self.boxInfo.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.lblheight)
        self.xtxHeight = QtWidgets.QPlainTextEdit(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.xtxHeight.sizePolicy().hasHeightForWidth())
        self.xtxHeight.setSizePolicy(sizePolicy)
        self.xtxHeight.setMaximumSize(QtCore.QSize(500, 16777215))
        self.xtxHeight.setObjectName("xtxHeight")
        self.boxInfo.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.xtxHeight)
        self.lblLegLength = QtWidgets.QLabel(self.gridLayoutWidget)
        self.lblLegLength.setObjectName("lblLegLength")
        self.boxInfo.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.lblLegLength)
        self.txtLegLength = QtWidgets.QPlainTextEdit(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txtLegLength.sizePolicy().hasHeightForWidth())
        self.txtLegLength.setSizePolicy(sizePolicy)
        self.txtLegLength.setMaximumSize(QtCore.QSize(500, 16777215))
        self.txtLegLength.setObjectName("txtLegLength")
        self.boxInfo.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.txtLegLength)
        self.gridLayout.addLayout(self.boxInfo, 0, 0, 1, 1)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.lblPort = QtWidgets.QLabel(self.gridLayoutWidget)
        self.lblPort.setObjectName("lblPort")
        self.gridLayout_2.addWidget(self.lblPort, 1, 0, 1, 1)
        self.txtPort = QtWidgets.QTextEdit(self.gridLayoutWidget)
        self.txtPort.setObjectName("txtPort")
        self.gridLayout_2.addWidget(self.txtPort, 1, 1, 1, 1)
        self.btnConnect = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.btnConnect.setObjectName("btnConnect")
        self.gridLayout_2.addWidget(self.btnConnect, 2, 1, 1, 1)
        self.txtHost = QtWidgets.QPlainTextEdit(self.gridLayoutWidget)
        self.txtHost.setObjectName("txtHost")
        self.gridLayout_2.addWidget(self.txtHost, 0, 1, 1, 1)
        self.lblost = QtWidgets.QLabel(self.gridLayoutWidget)
        self.lblost.setObjectName("lblost")
        self.gridLayout_2.addWidget(self.lblost, 0, 0, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_2, 0, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1025, 27))
        self.menubar.setObjectName("menubar")
        self.menuSubject = QtWidgets.QMenu(self.menubar)
        self.menuSubject.setObjectName("menuSubject")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menuSubject.menuAction())

        self.retranslateUi(MainWindow)

        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btnStartSession.setText(_translate("MainWindow", "Start Session"))
        self.btnOpenMonitor.setText(_translate("MainWindow", "open monitor"))
        self.lblTrialNumber.setText(_translate("MainWindow", "Trial 00"))
        self.btnRecord.setText(_translate("MainWindow", "Record"))
        self.btnStop.setText(_translate("MainWindow", "Stop"))
        self.lblSubject.setText(_translate("MainWindow", "Subject number"))
        self.lblAge.setText(_translate("MainWindow", "Age"))
        self.lblGender.setText(_translate("MainWindow", "Gender"))
        self.lblMass.setText(_translate("MainWindow", "Mass"))
        self.lblheight.setText(_translate("MainWindow", "Height"))
        self.lblLegLength.setText(_translate("MainWindow", "Leg Length"))
        self.lblPort.setText(_translate("MainWindow", "port"))
        self.btnConnect.setText(_translate("MainWindow", "Connect to Exo"))
        self.lblost.setText(_translate("MainWindow", "host"))
        self.menuSubject.setTitle(_translate("MainWindow", "Subject "))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)

    ui = Ui_MainWindow()

    sys.exit(app.exec_())

