# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Subject_Tester.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtWidgets

from Managers import SessionManger


class Ui_MainWindow(SessionManger.SessionManager):

    def __init__(self):
        self.MainWindow = QtWidgets.QMainWindow()
        self.setupUi(self.MainWindow)

        lbl_ = [self.lblAge, self.lblGender, self.lblheight, self.lblLegLength, self.lblheight, self.lblMass,
                self.lblTrialNumber, self.lblPort]
        btn_ = [self.btnConnect, self.btnOpenMonitor, self.btnRecord, self.btnStartSession, self.btnStop]
        txt_ = [self.txtAge, self.txtGender, self.txtHost, self.txtLegLength, self.txtMass, self.txtPort,
                self.txtSubject, self.txtHeight]

        super(Ui_MainWindow, self).__init__(btn_, txt_, lbl_)

        self.MainWindow.show()

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(988, 347)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.btnConnect = QtWidgets.QPushButton(self.centralwidget)
        self.btnConnect.setGeometry(QtCore.QRect(503, 110, 135, 27))
        self.btnConnect.setObjectName("btnConnect")
        self.lblTrialNumber = QtWidgets.QLabel(self.centralwidget)
        self.lblTrialNumber.setGeometry(QtCore.QRect(783, 100, 57, 19))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblTrialNumber.sizePolicy().hasHeightForWidth())
        self.lblTrialNumber.setSizePolicy(sizePolicy)
        self.lblTrialNumber.setObjectName("lblTrialNumber")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(30, 10, 387, 191))
        self.widget.setObjectName("widget")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.widget)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.lblAge = QtWidgets.QLabel(self.widget)
        self.lblAge.setObjectName("lblAge")
        self.gridLayout_3.addWidget(self.lblAge, 1, 0, 1, 1)
        self.lblMass = QtWidgets.QLabel(self.widget)
        self.lblMass.setObjectName("lblMass")
        self.gridLayout_3.addWidget(self.lblMass, 3, 0, 1, 1)
        self.lblGender = QtWidgets.QLabel(self.widget)
        self.lblGender.setObjectName("lblGender")
        self.gridLayout_3.addWidget(self.lblGender, 2, 0, 1, 1)
        self.lblSubject = QtWidgets.QLabel(self.widget)
        self.lblSubject.setObjectName("lblSubject")
        self.gridLayout_3.addWidget(self.lblSubject, 0, 0, 1, 1)
        self.txtSubject = QtWidgets.QPlainTextEdit(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txtSubject.sizePolicy().hasHeightForWidth())
        self.txtSubject.setSizePolicy(sizePolicy)
        self.txtSubject.setMaximumSize(QtCore.QSize(500, 16777215))
        self.txtSubject.setObjectName("txtSubject")
        self.gridLayout_3.addWidget(self.txtSubject, 0, 1, 1, 1)
        self.txtMass = QtWidgets.QPlainTextEdit(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txtMass.sizePolicy().hasHeightForWidth())
        self.txtMass.setSizePolicy(sizePolicy)
        self.txtMass.setMaximumSize(QtCore.QSize(500, 16777215))
        self.txtMass.setObjectName("txtMass")
        self.gridLayout_3.addWidget(self.txtMass, 3, 1, 1, 1)
        self.lblheight = QtWidgets.QLabel(self.widget)
        self.lblheight.setObjectName("lblheight")
        self.gridLayout_3.addWidget(self.lblheight, 4, 0, 1, 1)
        self.lblLegLength = QtWidgets.QLabel(self.widget)
        self.lblLegLength.setObjectName("lblLegLength")
        self.gridLayout_3.addWidget(self.lblLegLength, 5, 0, 1, 1)
        self.txtAge = QtWidgets.QPlainTextEdit(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txtAge.sizePolicy().hasHeightForWidth())
        self.txtAge.setSizePolicy(sizePolicy)
        self.txtAge.setMaximumSize(QtCore.QSize(500, 16777215))
        self.txtAge.setObjectName("txtAge")
        self.gridLayout_3.addWidget(self.txtAge, 1, 1, 1, 1)
        self.txtLegLength = QtWidgets.QPlainTextEdit(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txtLegLength.sizePolicy().hasHeightForWidth())
        self.txtLegLength.setSizePolicy(sizePolicy)
        self.txtLegLength.setMaximumSize(QtCore.QSize(500, 16777215))
        self.txtLegLength.setObjectName("txtLegLength")
        self.gridLayout_3.addWidget(self.txtLegLength, 5, 1, 1, 1)
        self.txtGender = QtWidgets.QPlainTextEdit(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txtGender.sizePolicy().hasHeightForWidth())
        self.txtGender.setSizePolicy(sizePolicy)
        self.txtGender.setMaximumSize(QtCore.QSize(500, 16777215))
        self.txtGender.setObjectName("txtGender")
        self.gridLayout_3.addWidget(self.txtGender, 2, 1, 1, 1)
        self.txtHeight = QtWidgets.QPlainTextEdit(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txtHeight.sizePolicy().hasHeightForWidth())
        self.txtHeight.setSizePolicy(sizePolicy)
        self.txtHeight.setMaximumSize(QtCore.QSize(500, 16777215))
        self.txtHeight.setObjectName("txtHeight")
        self.gridLayout_3.addWidget(self.txtHeight, 4, 1, 1, 1)
        self.widget1 = QtWidgets.QWidget(self.centralwidget)
        self.widget1.setGeometry(QtCore.QRect(433, 20, 300, 81))
        self.widget1.setObjectName("widget1")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.widget1)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.lblost = QtWidgets.QLabel(self.widget1)
        self.lblost.setObjectName("lblost")
        self.gridLayout_4.addWidget(self.lblost, 0, 0, 1, 1)
        self.txtHost = QtWidgets.QPlainTextEdit(self.widget1)
        self.txtHost.setObjectName("txtHost")
        self.gridLayout_4.addWidget(self.txtHost, 0, 1, 1, 1)
        self.lblPort = QtWidgets.QLabel(self.widget1)
        self.lblPort.setObjectName("lblPort")
        self.gridLayout_4.addWidget(self.lblPort, 1, 0, 1, 1)
        self.txtPort = QtWidgets.QTextEdit(self.widget1)
        self.txtPort.setObjectName("txtPort")
        self.gridLayout_4.addWidget(self.txtPort, 1, 1, 1, 1)
        self.widget2 = QtWidgets.QWidget(self.centralwidget)
        self.widget2.setGeometry(QtCore.QRect(753, 20, 125, 62))
        self.widget2.setObjectName("widget2")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.widget2)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.btnStartSession = QtWidgets.QPushButton(self.widget2)
        self.btnStartSession.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnStartSession.sizePolicy().hasHeightForWidth())
        self.btnStartSession.setSizePolicy(sizePolicy)
        self.btnStartSession.setObjectName("btnStartSession")
        self.gridLayout_5.addWidget(self.btnStartSession, 0, 0, 1, 1)
        self.btnOpenMonitor = QtWidgets.QPushButton(self.widget2)
        self.btnOpenMonitor.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnOpenMonitor.sizePolicy().hasHeightForWidth())
        self.btnOpenMonitor.setSizePolicy(sizePolicy)
        self.btnOpenMonitor.setObjectName("btnOpenMonitor")
        self.gridLayout_5.addWidget(self.btnOpenMonitor, 1, 0, 1, 1)
        self.widget3 = QtWidgets.QWidget(self.centralwidget)
        self.widget3.setGeometry(QtCore.QRect(883, 20, 87, 62))
        self.widget3.setObjectName("widget3")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.widget3)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.btnStop = QtWidgets.QPushButton(self.widget3)
        self.btnStop.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnStop.sizePolicy().hasHeightForWidth())
        self.btnStop.setSizePolicy(sizePolicy)
        self.btnStop.setMaximumSize(QtCore.QSize(600, 16777215))
        self.btnStop.setObjectName("btnStop")
        self.gridLayout_6.addWidget(self.btnStop, 2, 0, 1, 1)
        self.btnRecord = QtWidgets.QPushButton(self.widget3)
        self.btnRecord.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnRecord.sizePolicy().hasHeightForWidth())
        self.btnRecord.setSizePolicy(sizePolicy)
        self.btnRecord.setMaximumSize(QtCore.QSize(200, 16777215))
        self.btnRecord.setObjectName("btnRecord")
        self.gridLayout_6.addWidget(self.btnRecord, 1, 0, 1, 1)
        self.lblSubject.raise_()
        self.txtAge.raise_()
        self.lblAge.raise_()
        self.lblSubject.raise_()
        self.lblSubject.raise_()
        self.txtSubject.raise_()
        self.txtAge.raise_()
        self.lblAge.raise_()
        self.lblGender.raise_()
        self.txtGender.raise_()
        self.lblGender.raise_()
        self.txtMass.raise_()
        self.lblMass.raise_()
        self.txtHeight.raise_()
        self.lblheight.raise_()
        self.txtLegLength.raise_()
        self.lblLegLength.raise_()
        self.txtHost.raise_()
        self.lblost.raise_()
        self.txtPort.raise_()
        self.lblPort.raise_()
        self.btnConnect.raise_()
        self.btnStartSession.raise_()
        self.btnOpenMonitor.raise_()
        self.lblTrialNumber.raise_()
        self.btnRecord.raise_()
        self.btnStop.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 988, 27))
        self.menubar.setObjectName("menubar")
        self.menuSubject = QtWidgets.QMenu(self.menubar)
        self.menuSubject.setObjectName("menuSubject")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menuSubject.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btnConnect.setText(_translate("MainWindow", "Connect to Exo"))
        self.lblTrialNumber.setText(_translate("MainWindow", "Trial 00"))
        self.lblAge.setText(_translate("MainWindow", "Age"))
        self.lblMass.setText(_translate("MainWindow", "Mass"))
        self.lblGender.setText(_translate("MainWindow", "Gender"))
        self.lblSubject.setText(_translate("MainWindow", "Subject number"))
        self.lblheight.setText(_translate("MainWindow", "Height"))
        self.lblLegLength.setText(_translate("MainWindow", "Leg Length"))
        self.lblost.setText(_translate("MainWindow", "host"))
        self.lblPort.setText(_translate("MainWindow", "port"))
        self.btnStartSession.setText(_translate("MainWindow", "Start Session"))
        self.btnOpenMonitor.setText(_translate("MainWindow", "open monitor"))
        self.btnStop.setText(_translate("MainWindow", "Stop"))
        self.btnRecord.setText(_translate("MainWindow", "Record"))
        self.menuSubject.setTitle(_translate("MainWindow", "Subject "))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ui = Ui_MainWindow()
    sys.exit(app.exec_())

