Counter_Left_Foot:
  block1: 3
  block2: 4
  block3: 5
  type: "Counter"
  axis: "z"
  side: "Left"
  location: "Foot"

Accel_Left_Foot:
  block1: 6
  block2: 11
  block3: -1
  type: "Accel"
  axis: "zyx"
  side: "Left"
  location: "Foot"

Gyro_Left_Foot:
  block1: 12
  block2: 17
  block3: -1
  type: "Gyro"
  axis: "zyx"
  side: "Left"
  location: "Foot"

rshal_Left_Foot:
  block1: 18
  block2: 19
  block3: -1
  type: "rshal"
  axis: "z"
  side: "Left"
  location: "Foot"

Temperature_Left_Foot:
  block1: 20
  block2: 21
  block3: -1
  type: "Temperature"
  axis: "z"
  side: "Left"
  location: "Foot"

Counter_Right_Foot:
  block1: 22
  block2: 23
  block3: 24
  type: "Counter"
  axis: "z"
  side: "Right"
  location: "Foot"

Accel_Right_Foot:
  block1: 25
  block2: 30
  block3: -1
  type: "Accel"
  axis: "zyx"
  side: "Right"
  location: "Foot"

Gyro_Right_Foot:
  block1: 31
  block2: 36
  block3: -1
  type: "Gyro"
  axis: "zyx"
  side: "Right"
  location: "Foot"

rshal_Right_Foot:
  block1: 37
  block2: 38
  block3: -1
  type: "rshal"
  axis: "z"
  side: "Right"
  location: "Foot"

Temperature_Right_Foot:
  block1: 39
  block2: 40
  block3: -1
  type: "Temperature"
  axis: "z"
  side: "Right"
  location: "Foot"

Counter_Left_Ankle:
  block1: 41
  block2: 42
  block3: 43
  type: "Counter"
  axis: "z"
  side: "Left"
  location: "Ankle"

Accel_Left_Ankle:
  block1: 44
  block2: 49
  block3: -1
  type: "Accel"
  axis: "zyx"
  side: "Left"
  location: "Ankle"

Gyro_Left_Ankle:
  block1: 50
  block2: 55
  block3: -1
  type: "Gyro"
  axis: "zyx"
  side: "Left"
  location: "Ankle"

rshal_Left_Ankle:
  block1: 56
  block2: 57
  block3: -1
  type: "rshal"
  axis: "z"
  side: "Left"
  location: "Ankle"

Temperature_Left_Ankle:
  block1: 58
  block2: 59
  block3: -1
  type: "Temperature"
  axis: "z"
  side: "Left"
  location: "Ankle"

Counter_Right_Ankle:
  block1: 60
  block2: 61
  block3: 62
  type: "Counter"
  axis: "z"
  side: "Right"
  location: "Ankle"

Accel_Right_Ankle:
  block1: 63
  block2: 74
  block3: -1
  type: "Accel"
  axis: "zyx"
  side: "Right"
  location: "Ankle"

Gyro_Right_Ankle:
  block1: 69
  block2: 74
  block3: -1
  type: "Gyro"
  axis: "zyx"
  side: "Right"
  location: "Ankle"

rshal_Right_Ankle:
  block1: 75
  block2: 76
  block3: -1
  type: "rshal"
  axis: "z"
  side: "Right"
  location: "Ankle"

Temperature_Right_Ankle:
  block1: 77
  block2: 78
  block3: -1
  type: "Temperature"
  axis: "z"
  side: "Right"
  location: "Ankle"


Counter_Left_Knee:
  block1: 79
  block2: 80
  block3: 81
  type: "Counter"
  axis: "z"
  side: "Left"
  location: "Knee"

Accel_Left_Knee:
  block1: 82
  block2: 87
  block3: -1
  type: "Accel"
  axis: "zyx"
  side: "Left"
  location: "Knee"

Gyro_Left_Knee:
  block1: 88
  block2: 93
  block3: -1
  type: "Gyro"
  axis: "zyx"
  side: "Left"
  location: "Knee"

rshal_Left_Knee:
  block1: 94
  block2: 95
  block3: -1
  type: "rshal"
  axis: "z"
  side: "Left"
  location: "Knee"

Temperature_Left_Knee:
  block1: 96
  block2: 97
  block3: -1
  type: "Temperature"
  axis: "z"
  side: "Left"
  location: "Knee"

Counter_Right_Knee:
  block1: 98
  block2: 99
  block3: 100
  type: "Counter"
  axis: "z"
  side: "Right"
  location: "Knee"

Accel_Right_Knee:
  block1: 101
  block2: 106
  block3: -1
  type: "Accel"
  axis: "zxy"
  side: "Right"
  location: "Knee"

Gyro_Right_Knee:
  block1: 107
  block2: 112
  block3: -1
  type: "Gyro"
  axis: "zyx"
  side: "Right"
  location: "Knee"

rshal_Right_Knee:
  block1: 113
  block2: 114
  block3: -1
  type: "rshal"
  axis: "z"
  side: "Right"
  location: "Knee"

Temperature_Right_Knee:
  block1: 115
  block2: 116
  block3: -1
  type: "Temperature"
  axis: "z"
  side: "Right"
  location: "Knee"

Counter_Center:
  block1: 117
  block2: 118
  block3: 119
  type: "Counter"
  axis: "z"
  side: "Center"
  location: "Center"

Accel_Center:
  block1: 120
  block2: 125
  block3: -1
  type: "Accel"
  axis: "zyx"
  side: "Center"
  location: "Center"

Gyro_Center:
  block1: 126
  block2: 131
  block3: -1
  type: "Gyro"
  axis: "z"
  side: "Center"
  location: "Center"

rshal_Center:
  block1: 132
  block2: 133
  block3: -1
  type: "rshal"
  axis: "z"
  side: "Center"
  location: "Center"

Temperature_Center:
  block1: 134
  block2: 135
  block3: -1
  type: "Temperature"
  axis: "z"
  side: "Center"
  location: "Center"

Pot_Left_Ankle:
  block1: 136
  block2: 137
  block3: -1
  type: "Pot"
  axis: "z"
  side: "Left"
  location: "Ankle"

Pot_Right_Ankle:
  block1: 138
  block2: 139
  block3: -1
  type: "Pot"
  axis: "z"
  side: "Right"
  location: "Ankle"

Pot_Left_Knee:
  block1: 140
  block2: 141
  block3: -1
  type: "Pot"
  axis: "z"
  side: "Left"
  location: "Knee"

Pot_Right_Knee:
  block1: 142
  block2: 143
  block3: -1
  type: "Pot"
  axis: "z"
  side: "Right"
  location: "Knee"

Pot_Left_Hip:
  block1: 144
  block2: 145
  block3: -1
  type: "Pot"
  axis: "z"
  side: "Left"
  location: "Hip"

Pot_Right_Hip:
  block1: 146
  block2: 147
  block3: -1
  type: "Pot"
  axis: "z"
  side: "Right"
  location: "Hip"

FSR1_Right:
  block1: 148
  block2: 149
  block3: -1
  type: "FSR"
  axis: "z"
  side: "Right"
  location: "Foot"

FSR2_Right:
  block1: 150
  block2: 151
  block3: -1
  type: "FSR"
  axis: "z"
  side: "Right"
  location: "Foot"

FSR3_Right:
  block1: 152
  block2: 153
  block3: -1
  type: "FSR"
  axis: "z"
  side: "Right"
  location: "Foot"


FSR1_Left:
  block1: 154
  block2: 155
  block3: -1
  type: "FSR"
  axis: "z"
  side: "Left"
  location: "Foot"

FSR2_Left:
  block1: 156
  block2: 157
  block3: -1
  type: "FSR"
  axis: "z"
  side: "Left"
  location: "Foot"

FSR3_Left:
  block1: 158
  block2: 159
  block3: -1
  type: "FSR"
  axis: "z"
  side: "Left"
  location: "Foot"

IMU_Left_Ankle:
  accel: "Accel_Left_Ankle"
  gyro: "Gyro_Left_Ankle"
  temp: "Temperature_Left_Ankle"
  count: "Counter_Left_Ankle"
  rshal: "rshal_Left_Ankle"
  side: "Left"
  location: "Foot"
  type: "IMU"

IMU_Right_Ankle:
  accel: "Accel_Right_Ankle"
  gyro: "Gyro_Right_Ankle"
  temp: "Temperature_Right_Ankle"
  count: "Counter_Right_Ankle"
  rshal: "rshal_Right_Ankle"
  side: "Right"
  location: "Foot"
  type: "IMU"

IMU_Left_Knee:
  accel: "Accel_Left_Knee"
  gyro: "Gyro_Left_Knee"
  temp: "Temperature_Left_Knee"
  count: "Counter_Left_Knee"
  rshal: "rshal_Left_Knee"
  side: "Left"
  location: "Knee"
  type: "IMU"

IMU_Right_Knee:
  accel: "Accel_Right_Knee"
  gyro: "Gyro_Right_Knee"
  temp: "Temperature_Right_Knee"
  count: "Counter_Right_Knee"
  rshal: "rshal_Right_Knee"
  side: "Right"
  location: "Knee"
  type: "IMU"

IMU_Left_Hip:
  accel: "Accel_Left_Hip"
  gyro: "Gyro_Left_Hip"
  temp: "Temperature_Left_Hip"
  count: "Counter_Left_Hip"
  rshal: "rshal_Left_Hip"
  side: "Left"
  location: "Hip"
  type: "IMU"

IMU_Right_Hip:
  accel: "Accel_Right_Hip"
  gyro: "Gyro_Right_Hip"
  temp: "Temperature_Right_Hip"
  count: "Counter_Right_Hip"
  rshal: "rshal_Right_Hip"
  side: "Right"
  location: "Hip"
  type: "IMU"

IMU_Center:
  accel: "Accel_Center"
  gyro: "Gyro_Center"
  temp: "Temperature_Center"
  count: "Counter_Center"
  rshal: "rshal_Center"
  side: "Center"
  location: "Center"
  type: "IMU"